name: Frontend CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Install linter
      - name: Install Linter
        run: pip install flake8

      # Lint the code
      - name: Lint Code
        run: flake8 index.html

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t frontend-service:ci .
